com.kiransprojects.travelme/com.kiransprojects.travelme/Controllers/TripController.cs
namespace com.kiransprojects.travelme.Controllers
{
    using com.kiransprojects.travelme.Framework.Entities;
    using com.kiransprojects.travelme.Services.Interfaces;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    /// <summary>
    /// Trip Controller
    /// </summary>
    [Authorize]
    public class TripController : BaseController
    {
        private readonly ITripService _tripService = null; 

        /// <summary>
        /// Initializes a new instance of the <see cref="TripController"/> class.
        /// </summary>
        /// <param name="logger">Logger Service</param>
        /// <param name="tripService">Trip Service</param>
        public TripController(
            ILoggerService logger, 
            ITripService tripService ) 
            : base(logger)
        {
            if(tripService == null)
            {
                throw new ArgumentNullException("Trip Service, Trip Controller"); 
            }

            this._tripService = tripService; 
        }
        
        /// <summary>
        /// Gets trips for the user
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult Index(string ID)
        {
            if(string.IsNullOrEmpty(ID))
            {
                return this.RedirectToAction("Index", "Home"); 
            }

            IList<Trip> trips = this._tripService.GetTrips(Guid.Parse(ID)); 

            return this.View("Index",trips);
        }
    }
}

com.kiransprojects.travelme/com.kiransprojects.travelme/Controllers/UserController.cs
namespace com.kiransprojects.travelme.Controllers
{
    using com.kiransprojects.travelme.Framework.Entities;
    using com.kiransprojects.travelme.Models;
    using com.kiransprojects.travelme.Services.Interfaces;
    using System;
    using System.Web.Mvc; 

    /// <summary>
    /// User Controller
    /// </summary>
    public class UserController : BaseController
    {
        /// <summary>
        /// User Service
        /// </summary>
        private readonly IUserService userService = null;

        /// <summary>
        /// Trip Service
        /// </summary>
        private readonly ITripService tripService = null;

        /// <summary>
        /// Post Service
        /// </summary>
        private readonly IPostService postService = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserController"/> class.
        /// </summary>
        /// <param name="loggerService">Logger Service</param>
        /// <param name="userService">User Service</param>
        /// <param name="tripService">Trip Service</param>
        /// <param name="postService">Post Service</param>
        public UserController(
            ILoggerService loggerService,
            IUserService userService,
            ITripService tripService,
            IPostService postService) 
            : base(loggerService)
        {
            if(userService == null)
            {
                throw new ArgumentNullException("User Service, User Controller");
            }

            if (tripService == null)
            {
                throw new ArgumentNullException("Trip Service, User Controller");
            }

            if (postService == null)
            {
                throw new ArgumentNullException("Post Service, User Controller");
            }

            this.userService = userService;
            this.tripService = tripService;
            this.postService = postService;
        }

        public string Index()
        {
            return "test";
        }

        /// <summary>
        /// Home page for a logged in user
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Home(string ID)
        {
            UserViewModel model = new UserViewModel(); 
            model.User = this.userService.GetUser(Guid.Parse(ID));
            return this.View(model);
        }

    }
}

com.kiransprojects.travelme/com.kiransprojects.travelme/Views/Shared/Footer.cshtml
<div class="row">
    <div class="col-xs-12">
        <div id="footer">
            &copy; @string.Format("{0} - {1}", ViewBag.Title, DateTime.Now.Year)
        </div>
    </div>
</div>

com.kiransprojects.travelme/com.kiransprojects.travelme/Views/Shared/Navigation.cshtml
<div class="row">
    <div class="col-sm-12 hidden-xs">
        <nav id="nav">
            <ul>
                <li>travel me</li>
                <li>@Html.ActionLink("Home", "Home", "User")</li>
                <li>@Html.ActionLink("Trips", "Trips", "Trip")</li>
                <li>@Html.ActionLink("Locations", "Locations", "User")</li>
                <li>@Html.ActionLink("Profile", "Profile", "User")</li>
            </ul>
        </nav>
    </div>
</div>

com.kiransprojects.travelme/com.kiransprojects.travelme/Views/Shared/PartialAddTrip.cshtml
@model com.kiransprojects.travelme.Framework.Entities.Trip

<h3>Add Trip</h3>

@using(Html.BeginForm("Add", "Trip", FormMethod.Post, null)) 
{
    @Html.ValidationSummary()

    @Html.LabelFor(model => Model.TripName)
    @Html.TextAreaFor(model => Model.TripName)
    <br />

    @Html.LabelFor(model => Model.TripDescription)
    @Html.TextAreaFor(model => Model.TripDescription)
    <br />

    @Html.LabelFor(model => Model.TripLocation)
    @Html.TextAreaFor(model => Model.TripLocation)
    <br />


    @Html.HiddenFor(model => Model.RelationID)

    <input type="submit" value="Add" class="button"/>
}

com.kiransprojects.travelme/com.kiransprojects.travelme/Views/Shared/PartialListTrips.cshtml
@model IList<com.kiransprojects.travelme.Framework.Entities.Trip>
@using com.kiransprojects.travelme.Extensions
@using com.kiransprojects.travelme.Framework.Entities;

<h3>Previous Trips</h3>
@if (Model != null)
{
    for (int i = 0; i < Model.Count; i++)
    {
        @Html.DisplayFor(model => model[0].TripName)
        <hr />
        @Html.DisplayFor(model => model[0].TripDescription)
        <hr />
    }
}
else
{
    <p>No Trips</p>
}

com.kiransprojects.travelme/com.kiransprojects.travelme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("http://anijs.github.io/lib/anicollection/anicollection.css")
    @Styles.Render("https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css")
    @Styles.Render("~/Content/Site.min.css")
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>

    @Html.Partial("Footer")
       
    @*@RenderSection("scripts", required: false)*@
    @Scripts.Render("~/Scripts/jquery-1.9.1.min.js")
    @Scripts.Render("https://cdn.jsdelivr.net/anijs/0.9.3/anijs-min.js")
    @Scripts.Render("~/Scripts/Custom/HomeAnimations.js")
</body>
</html>